# -*- coding: utf-8 -*-
"""Arabic_LLM_Finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSA2c9afMxh4yW9qWk04VnfhWtLJE_JZ

# Arabic LLM Performance Improvement
## Fine-tuning AraBERT for Arabic Text Classification

**Course:** Generative AI with LLMs – AI496  
**Student:** Shatha Adel Mahrous | 4210833  
**Supervisor:** Dr. Soumaya Chaffar  
**University:** University of Prince Mugrin

---

### Objective
This notebook demonstrates how fine-tuning AraBERT on an Arabic text classification dataset improves model performance. We compare accuracy and F1-score **before** and **after** fine-tuning.

### Dataset
We use the **AJGT (Arabic Jordanian General Tweets)** dataset — a publicly available binary sentiment classification dataset containing Arabic tweets labeled as Positive or Negative.

### Model
**AraBERT v2** (`aubmindlab/bert-base-arabertv02`) — a BERT-based model pre-trained on large Arabic corpora.

## Step 1: Install Required Libraries
"""

!pip install transformers datasets torch scikit-learn matplotlib seaborn arabert -q

"""## Step 2: Import Libraries"""

import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Check GPU availability
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')
print(f'PyTorch version: {torch.__version__}')

"""## Step 3: Load and Explore the Dataset"""

!pip install -U datasets huggingface_hub

from datasets import load_dataset

dataset = load_dataset("komari6/ajgt_twitter_ar")
print(dataset)

from collections import Counter
from datasets import load_dataset
import matplotlib.pyplot as plt

# Load dataset
dataset = load_dataset("komari6/ajgt_twitter_ar")

# Split train into train and test
split_dataset = dataset['train'].train_test_split(
    test_size=0.2,
    seed=42
)

train_data = split_dataset['train']
test_data = split_dataset['test']

print(f"Training samples : {len(train_data)}")
print(f"Test samples     : {len(test_data)}")

# Label distribution
train_labels = [item['label'] for item in train_data]
test_labels = [item['label'] for item in test_data]

# Label names
label_names = {
    0: 'Negative',
    1: 'Positive'
}

print("\nTrain label distribution:")
print({label_names[k]: v for k, v in Counter(train_labels).items()})

print("\nTest label distribution:")
print({label_names[k]: v for k, v in Counter(test_labels).items()})

# Plot distribution
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, labels, title in zip(
    axes,
    [train_labels, test_labels],
    ['Train Set', 'Test Set']
):
    counts = Counter(labels)

    ax.bar(
        [label_names[k] for k in sorted(counts)],
        [counts[k] for k in sorted(counts)],
        alpha=0.85,
        edgecolor='black'
    )

    ax.set_title(f'Label Distribution – {title}',
                 fontsize=13,
                 fontweight='bold')
    ax.set_ylabel('Count')

    for i, (k, v) in enumerate(sorted(counts.items())):
        ax.text(i, v + 5, str(v),
                ha='center',
                fontweight='bold')

plt.tight_layout()
plt.savefig('label_distribution.png',
            dpi=150,
            bbox_inches='tight')
plt.show()

# Show sample texts
print("=" * 60)
print("Sample Arabic texts from the dataset:")
print("=" * 60)
for i in range(5):
    sample = train_data[i]
    lbl = label_names[sample['label']]
    print(f"[{lbl}] {sample['text']}")
    print("-" * 60)

"""## Step 4: Load AraBERT Tokenizer"""

MODEL_NAME = "aubmindlab/bert-base-arabertv02"
NUM_LABELS = 2
MAX_LENGTH = 128

print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Test tokenizer on an Arabic sentence
sample_text = "الخدمة كانت رائعة جداً وسعر معقول"
tokens = tokenizer(sample_text, return_tensors='pt')
print(f"\nSample text: {sample_text}")
print(f"Token IDs  : {tokens['input_ids'][0].tolist()}")
print(f"Token count: {tokens['input_ids'].shape[1]}")

def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=MAX_LENGTH
    )

print("Tokenizing datasets...")
tokenized_train = train_data.map(tokenize_function, batched=True)
tokenized_test  = test_data.map(tokenize_function, batched=True)

# Rename 'label' -> 'labels' (required by Trainer)
tokenized_train = tokenized_train.rename_column("label", "labels")
tokenized_test  = tokenized_test.rename_column("label", "labels")

tokenized_train.set_format('torch', columns=['input_ids', 'attention_mask', 'labels'])
tokenized_test.set_format('torch',  columns=['input_ids', 'attention_mask', 'labels'])

print(f"Tokenized train size : {len(tokenized_train)}")
print(f"Tokenized test size  : {len(tokenized_test)}")

"""## Step 5: Baseline Evaluation (Before Fine-tuning)

We load the pre-trained AraBERT **without any fine-tuning** and evaluate it on the test set to establish a baseline.
"""

import numpy as np
from transformers import (
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import accuracy_score, f1_score

# Evaluation metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')

    return {
        "accuracy": round(acc, 4),
        "f1": round(f1, 4)
    }

# Load baseline model
print("Loading baseline AraBERT model (no fine-tuning)...")

baseline_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS
)

# Evaluation arguments
baseline_args = TrainingArguments(
    output_dir="./baseline_eval",
    per_device_eval_batch_size=16,
    report_to="none"
)

# Trainer
baseline_trainer = Trainer(
    model=baseline_model,
    args=baseline_args,
    eval_dataset=tokenized_test,
    compute_metrics=compute_metrics
)

# Evaluate
print("Evaluating baseline...")

baseline_results = baseline_trainer.evaluate()

print("\n" + "=" * 40)
print("Baseline Results (Before Fine-tuning)")
print("=" * 40)
print(f"Accuracy : {baseline_results['eval_accuracy']:.4f}")
print(f"F1-Score : {baseline_results['eval_f1']:.4f}")

"""## Step 6: Fine-tune AraBERT"""

import numpy as np
from transformers import (
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)
from sklearn.metrics import accuracy_score, f1_score

# =========================
# Metrics
# =========================
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')

    return {
        "accuracy": round(acc, 4),
        "f1": round(f1, 4)
    }

# =========================
# Load Model
# =========================
print("Loading fresh AraBERT model for fine-tuning...")

finetuned_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS
)

# =========================
# Training Arguments (UPDATED FOR NEW TRANSFORMERS)
# =========================
training_args = TrainingArguments(
    output_dir="./arabert_finetuned",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_ratio=0.1,
    weight_decay=0.01,
    learning_rate=2e-5,
    logging_dir="./logs",
    logging_steps=50,

    # ✅ الجديد بدل evaluation_strategy
    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    report_to="none"
)

# =========================
# Trainer
# =========================
trainer = Trainer(
    model=finetuned_model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# =========================
# Train
# =========================
print("Starting fine-tuning...")

train_result = trainer.train()

print("\nFine-tuning complete!")
print(f"Total training steps : {train_result.global_step}")
print(f"Training runtime (s) : {train_result.metrics['train_runtime']:.1f}")

"""## Step 7: Evaluate Fine-tuned Model"""

print("Evaluating fine-tuned model...")
finetuned_results = trainer.evaluate()
print("\n" + "=" * 40)
print("Results After Fine-tuning:")
print("=" * 40)
print(f"Accuracy : {finetuned_results['eval_accuracy']:.4f}")
print(f"F1-Score : {finetuned_results['eval_f1']:.4f}")

# Improvement summary
acc_improvement = finetuned_results['eval_accuracy'] - baseline_results['eval_accuracy']
f1_improvement  = finetuned_results['eval_f1']       - baseline_results['eval_f1']
print(f"\nImprovement in Accuracy : +{acc_improvement:.4f}")
print(f"Improvement in F1-Score : +{f1_improvement:.4f}")

# Detailed classification report
predictions_output = trainer.predict(tokenized_test)
preds       = np.argmax(predictions_output.predictions, axis=-1)
labels_true = predictions_output.label_ids

print("Detailed Classification Report (Fine-tuned Model):")
print("=" * 55)
print(classification_report(labels_true, preds,
                             target_names=['Negative', 'Positive']))

"""## Step 8: Visualize Results"""

# Confusion Matrix
cm = confusion_matrix(labels_true, preds)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negative', 'Positive'],
            yticklabels=['Negative', 'Positive'],
            linewidths=0.5, linecolor='gray')
plt.title('Confusion Matrix – AraBERT Fine-tuned', fontsize=14, fontweight='bold')
plt.ylabel('True Label', fontsize=12)
plt.xlabel('Predicted Label', fontsize=12)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("Confusion matrix saved as 'confusion_matrix.png'")

# Before vs After Comparison Chart
metrics       = ['Accuracy', 'F1-Score']
before_values = [baseline_results['eval_accuracy'],   baseline_results['eval_f1']]
after_values  = [finetuned_results['eval_accuracy'],  finetuned_results['eval_f1']]

x     = np.arange(len(metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(9, 6))
bars1 = ax.bar(x - width/2, before_values, width,
               label='Before Fine-tuning', color='#FF6B6B', alpha=0.88, edgecolor='black')
bars2 = ax.bar(x + width/2, after_values,  width,
               label='After Fine-tuning',  color='#4ECDC4', alpha=0.88, edgecolor='black')

ax.set_xlabel('Metric', fontsize=12)
ax.set_ylabel('Score',  fontsize=12)
ax.set_title('AraBERT Performance: Before vs After Fine-tuning\n(AJGT Arabic Dataset)',
             fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics, fontsize=11)
ax.set_ylim(0, 1.15)
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3)

for bar in bars1:
    ax.annotate(f'{bar.get_height():.3f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 4), textcoords='offset points', ha='center', fontweight='bold')
for bar in bars2:
    ax.annotate(f'{bar.get_height():.3f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 4), textcoords='offset points', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('comparison_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print("Comparison chart saved as 'comparison_chart.png'")

# Training Loss Curve
history    = trainer.state.log_history
train_loss = [x['loss'] for x in history if 'loss' in x and 'eval_loss' not in x]
steps      = [x['step'] for x in history if 'loss' in x and 'eval_loss' not in x]

# Eval loss per epoch
eval_loss   = [x['eval_loss']     for x in history if 'eval_loss' in x]
eval_epochs = [x['epoch']         for x in history if 'eval_loss' in x]
eval_acc    = [x['eval_accuracy'] for x in history if 'eval_accuracy' in x]
eval_f1     = [x['eval_f1']       for x in history if 'eval_f1' in x]

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

axes[0].plot(steps, train_loss, color='#2196F3', linewidth=2)
axes[0].set_title('Training Loss', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Step');  axes[0].set_ylabel('Loss')
axes[0].grid(True, alpha=0.3)

axes[1].plot(eval_epochs, eval_acc, 'o-', color='#4CAF50', linewidth=2, markersize=8)
axes[1].set_title('Validation Accuracy per Epoch', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy')
axes[1].set_ylim(0, 1); axes[1].grid(True, alpha=0.3)

axes[2].plot(eval_epochs, eval_f1, 's-', color='#FF9800', linewidth=2, markersize=8)
axes[2].set_title('Validation F1-Score per Epoch', fontsize=12, fontweight='bold')
axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('F1-Score')
axes[2].set_ylim(0, 1); axes[2].grid(True, alpha=0.3)

plt.suptitle('AraBERT Fine-tuning Training Curves', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print("Training curves saved as 'training_curves.png'")

"""## Step 9: Results Summary Table"""

import pandas as pd

results_df = pd.DataFrame({
    'Model': ['AraBERT (Baseline)', 'AraBERT (Fine-tuned)'],
    'Accuracy': [
        f"{baseline_results['eval_accuracy']:.4f}",
        f"{finetuned_results['eval_accuracy']:.4f}"
    ],
    'F1-Score (Weighted)': [
        f"{baseline_results['eval_f1']:.4f}",
        f"{finetuned_results['eval_f1']:.4f}"
    ],
    'Improvement': [
        '-',
        f"+{finetuned_results['eval_accuracy'] - baseline_results['eval_accuracy']:.4f} Acc | "
        f"+{finetuned_results['eval_f1'] - baseline_results['eval_f1']:.4f} F1"
    ]
})

print("=" * 70)
print("RESULTS SUMMARY")
print("=" * 70)
print(results_df.to_string(index=False))
print("=" * 70)

"""## Step 10: Inference on Custom Arabic Texts"""

def predict_sentiment(texts, model, tokenizer, device='cpu'):
    """Predict sentiment for a list of Arabic texts."""
    model.eval()
    model.to(device)
    inputs = tokenizer(
        texts, padding=True, truncation=True,
        max_length=MAX_LENGTH, return_tensors='pt'
    ).to(device)
    with torch.no_grad():
        outputs    = model(**inputs)
        probs      = torch.softmax(outputs.logits, dim=-1)
        predictions = torch.argmax(probs, dim=-1)
    label_map = {0: 'Negative ❌', 1: 'Positive ✅'}
    return [
        {'text': t, 'label': label_map[p.item()],
         'confidence': f"{probs[i].max().item()*100:.1f}%"}
        for i, (t, p) in enumerate(zip(texts, predictions))
    ]

# Test with custom Arabic sentences
test_texts = [
    "الخدمة كانت رائعة والموظفون محترمون جداً",
    "تجربة سيئة جداً ولن أعود مرة أخرى",
    "المنتج ممتاز وسعره معقول جداً",
    "خدمة سيئة وتأخير في التسليم",
    "أنصح الجميع بزيارة هذا المكان، رائع حقاً",
    "لا أنصح بهذا المنتج أبداً، جودة سيئة"
]

results = predict_sentiment(test_texts, finetuned_model, tokenizer, device)

print("=" * 60)
print("Inference on Custom Arabic Texts:")
print("=" * 60)
for r in results:
    print(f"\nText       : {r['text']}")
    print(f"Prediction : {r['label']}  (Confidence: {r['confidence']})")
print("=" * 60)

"""## Conclusion

This notebook demonstrated the full pipeline for fine-tuning **AraBERT** on the **AJGT Arabic tweet sentiment dataset**:

1. **Baseline evaluation** showed that the pre-trained AraBERT without task-specific fine-tuning produces poor results on this binary classification task.
2. **Fine-tuning** for only 3 epochs produced a dramatic improvement in both Accuracy and F1-Score.
3. The **confusion matrix** and **classification report** confirm that the model learns to discriminate between positive and negative Arabic sentiment effectively.
4. **Custom inference** shows the model generalizes well to unseen Arabic sentences with high confidence.

### Key Findings
- Fine-tuning is highly effective even with a small dataset and just 3 training epochs.
- Dataset quality and pre-processing directly impact model performance.
- AraBERT is a strong foundation for Arabic NLP tasks when properly fine-tuned.

---
*University of Prince Mugrin | Generative AI with LLMs – AI496 | 2026*
"""